// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SentinelTrack.Infrastructure.Context;

#nullable disable

namespace SentinelTrack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523120222_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentinelTrack.Domain.Entities.Moto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Color")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Model")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("YardId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("YardId");

                    b.ToTable("ST_Motos", (string)null);
                });

            modelBuilder.Entity("SentinelTrack.Domain.Entities.Yard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ST_Yards", (string)null);
                });

            modelBuilder.Entity("SentinelTrack.Domain.Entities.Moto", b =>
                {
                    b.HasOne("SentinelTrack.Domain.Entities.Yard", "Yard")
                        .WithMany("Motos")
                        .HasForeignKey("YardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Yard");
                });

            modelBuilder.Entity("SentinelTrack.Domain.Entities.Yard", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
